apiVersion: v1
kind: ConfigMap
metadata:
  name: crash-loop-alert-rules
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
data:
  crash-loop-rules.yaml: |
    groups:
    - name: pod-crash-loops
      rules:
      - alert: PodCrashLooping
        expr: increase(kube_pod_container_status_restarts_total[5m]) > 3
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crashing"
          description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted more than 3 times in the last 5 minutes."
