apiVersion: v1
data:
  password: YWRtaW4=
  username: ZG9qX3Nhbm5p
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"password":"YWRtaW4=","username":"ZG9qX3Nhbm5p"},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":"2024-12-10T17:07:07Z","name":"db-secrets","namespace":"default","resourceVersion":"97226","uid":"ea05c93a-4401-48f8-8474-6781e9f58bcb"},"type":"Opaque"}
  creationTimestamp: "2024-12-10T17:07:07Z"
  name: db-secrets
  namespace: production
  resourceVersion: "97762"
  uid: ea05c93a-4401-48f8-8474-6781e9f58bcb
type: Opaque
