apiVersion: v1
kind: Secret
metadata:
  name: { ? { .Values.secrets.name } }
  namespace: { ? { .Values.namespace } }
type: Opaque
data:
  DATABASE_URI: { ? { .Values.secrets.databaseUri | b64enc } }
