name: CI/CD Pipeline with Rollback and Security Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set Up Python Environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install Dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run Unit Tests
    - name: Run tests
      run: |
        pytest

    # Step 5: Install Snyk CLI for Security Scanning
    - name: Install Snyk CLI
      run: |
        curl -fsSL https://static.snyk.io/cli/latest/snyk-linux -o /usr/local/bin/snyk
        chmod +x /usr/local/bin/snyk

    # Step 6: Authenticate with Snyk
    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    # Step 7: Scan Python Dependencies for Vulnerabilities
    - name: Snyk Dependency Scan
      run: snyk test --file=requirements.txt --package-manager=pip

    # Step 8: Build Docker Image
    - name: Build Docker image
      run: |
        docker build -t dgurutester/flask-app:${{ github.sha }} .

    # Step 9: Scan Docker Image for Vulnerabilities
    - name: Snyk Docker Scan
      run: snyk container test dgurutester/flask-app:${{ github.sha }}

    # Step 10: Push Docker Image to Docker Hub
    - name: Push Docker image to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        docker push dgurutester/flask-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step 1: Apply Kubernetes Secrets
    - name: Deploy Secrets
      run: kubectl apply -f db-secrets.yaml

    # Step 2: Deploy to Kubernetes
    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl apply -f flask-app-deployment.yaml
        kubectl apply -f flask-app-service.yaml
        kubectl apply -f flask-app-ingress.yaml

    # Step 3: Verify the Deployment
    - name: Verify Kubernetes Deployment
      run: kubectl rollout status deployment/flask-app

    # Step 4: Rollback on Failure
    - name: Rollback on Failure
      if: failure()
      run: kubectl rollout undo deployment/flask-app

    # Step 5: Notify via Slack (Optional)
    - name: Notify on Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,commit,author
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}